spring.application.name=PC
spring.datasource.url=jbdc:postgresql://${BD_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

spring.jwt.secret=${JWT_SECRET}
spring.jwt.expiration=${JWT_EXPIRATION}


